# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/view
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/view
Content-Type: application/json

{
  "name": "another_sensor",
  "description": "И еще один датчик"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/detailed/7
Content-Type: application/json

{
  "description": "Перенес еще в какое-то место"
}

###

# добавление измерения
POST {{baseUrl}}/sensors/measurement
Content-Type: application/json

{
  "sensor_id": 4,
  "temperature": 27.2
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/detailed/6
Content-Type: application/json
