# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/all
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/add
Content-Type: application/json

{
  "name": "new_sensor",
  "description": "Еще один датчик"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/update/5
Content-Type: application/json

{
  "description": "Перенес датчик еще куда-то"
}

###

# добавление измерения
POST {{baseUrl}}/sensors/measurement
Content-Type: application/json

{
  "sensor_id": 5,
  "temperature": 22.3
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/details/5
Content-Type: application/json
